/**
 * Canonical A4 playthrough transcript builder — the deterministic, sim-derived
 * data the minimal Windows desktop viewer (src/ui/shell) renders. Pure: given
 * the schema-validated storage + expedition seeds and a base seed, it drives
 * the REAL expedition sim (src/sim/expedition.ts) and records the state after
 * every command, so the on-screen loop is exactly what the sim produces —
 * never a hand-authored mock (CLAUDE.md §5; brief §2 minimal Windows interface).
 *
 * The committed transcript (src/ui/shell/playthrough.json) is generated by
 * scripts/build-playthrough.mts and drift-guarded by tests/expedition.test.ts:
 * a fresh build must byte-match the committed file, so the viewer can never
 * silently diverge from the sim.
 *
 * Governing docs: ALPHA_A4_EXECUTION_BRIEF v0.1 §2 (the player-facing loop),
 * §7 (Windows acceptance evidence). Invariant refs: mirrors the sim (OPS1,
 * conservation, overflow, EVT reuse); adds none of its own.
 */

import type { CoreResource } from "../contracts/enums.js";
import type { ExpeditionCommand, ResourceAmounts, StartingGuardianId } from "../contracts/expedition.js";
import type { ExpeditionSeed } from "../contracts/expedition-seed.js";
import type { ResourceStorageSeed } from "../contracts/resource-storage.js";
import {
  applyCommand,
  createExpeditionState,
  createHarborOperationsState,
  STARTING_GUARDIANS,
  type ExpeditionDomain,
} from "../sim/expedition.js";
import { CORE_RESOURCES, createHarborState } from "../sim/harbor-state.js";

/** One rendered step: the command applied and the resulting player-visible state. */
export interface PlaythroughStep {
  command: string;
  phase: string;
  note: string;
  harbor: Record<CoreResource, { safe: number; exposed: number }>;
  overflow: ResourceAmounts;
  cargo_aboard: ResourceAmounts;
}

/** One expedition run rendered end to end. */
export interface PlaythroughRun {
  title: string;
  guardian_id: string;
  steps: PlaythroughStep[];
}

/** The full transcript the viewer renders. */
export interface PlaythroughTranscript {
  content_id: string;
  route_id: string;
  outpost_id: string;
  seed: number;
  runs: PlaythroughRun[];
}

function snapshot(domain: ExpeditionDomain): Pick<PlaythroughStep, "harbor" | "overflow" | "cargo_aboard"> {
  const harbor = {} as Record<CoreResource, { safe: number; exposed: number }>;
  for (const resource of CORE_RESOURCES) {
    const band = domain.harbor.resources[resource];
    harbor[resource] = { safe: band.safe, exposed: band.exposed };
  }
  return {
    harbor,
    overflow: { ...domain.harbor_operations.overflow },
    cargo_aboard: { ...domain.expedition.active?.cargo_aboard },
  };
}

/**
 * Build the canonical transcript: one full-success loop for each starting
 * Guardian (showing the equal-total salvage arriving as a distinct resource,
 * and the unsafe Overflow being exercised), plus one cancellation run showing
 * the OPS1 supply refund. Deterministic given the seeds + base seed.
 */
export function buildPlaythrough(
  storageSeed: ResourceStorageSeed,
  expeditionSeed: ExpeditionSeed,
  seed: number,
): PlaythroughTranscript {
  const content = expeditionSeed.content;
  const ctx = { seed, content };

  const fresh = (): ExpeditionDomain => ({
    expedition: createExpeditionState(),
    harbor_operations: createHarborOperationsState(),
    harbor: createHarborState(storageSeed),
  });

  const runScript = (
    title: string,
    guardian: StartingGuardianId,
    commands: Array<{ command: ExpeditionCommand; note: string }>,
  ): PlaythroughRun => {
    let domain = fresh();
    const steps: PlaythroughStep[] = [];
    for (const { command, note } of commands) {
      const result = applyCommand(domain, command, ctx);
      domain = result.domain;
      steps.push({ command: command.kind, phase: domain.expedition.phase, note, ...snapshot(domain) });
    }
    return { title, guardian_id: guardian, steps };
  };

  const fullSuccessRun = (guardian: StartingGuardianId): PlaythroughRun => {
    const tag = guardian.replace(".", "_");
    return runScript(`Full success — ${guardian}`, guardian, [
      { command: { command_id: `${tag}.prepare`, kind: "prepare", guardian_id: guardian }, note: "Harbor need after Theo's funeral: prepare Theo's salvage vessel; supplies withdrawn onto the vessel." },
      { command: { command_id: `${tag}.dispatch`, kind: "dispatch" }, note: "Dispatch along the route; supplies are spent." },
      { command: { command_id: `${tag}.arrive`, kind: "arrive" }, note: "Arrive at the damaged route-anchor outpost; the stabilization objective begins (EVT4 trigger met)." },
      { command: { command_id: `${tag}.resolve`, kind: "resolve", outcome: "full_success" }, note: "Full success: recovered salvage loaded aboard (equal total, this Guardian's resource)." },
      { command: { command_id: `${tag}.dock`, kind: "dock" }, note: "Return and dock; review the result." },
      { command: { command_id: `${tag}.unload`, kind: "unload" }, note: "Unload: Safe Storage first, then unsafe Overflow (capped at 3× Safe) — every unit conserved." },
      { command: { command_id: `${tag}.complete`, kind: "complete" }, note: "Complete: route-anchor operations unlocked; ready to repeat." },
    ]);
  };

  const cancelRun = (): PlaythroughRun =>
    runScript("Cancellation (OPS1 refund)", "gdn.nova", [
      { command: { command_id: "cancel.prepare", kind: "prepare", guardian_id: "gdn.nova" }, note: "Prepare: supplies withdrawn onto the vessel." },
      { command: { command_id: "cancel.cancel", kind: "cancel" }, note: "Cancel before dispatch: supplies refunded directly to Harbor stock (Safe→Exposed) — never lost, never to the Ledger (OPS1)." },
    ]);

  return {
    content_id: content.content_id,
    route_id: content.route.route_id,
    outpost_id: content.outpost.outpost_id,
    seed,
    runs: [...STARTING_GUARDIANS.map(fullSuccessRun), cancelRun()],
  };
}
